name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy

    steps:
      - uses: actions/checkout@master

      - name: Publish
        uses: nogsantos/scp-deploy@master
        with:
          src: ./www/*
          host: ${{ secrets.STRATO_SSH_HOST }}
          remote: astronomikon
          port: 22
          user: ${{ secrets.STRATO_SSH_USER }}
          key: ${{ secrets.STRATO_SSH_KEY }}
